package com.randomteam.ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Slider;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AltaModificarComercial_ventana extends CssLayout {
	protected TextField nombreTF;
	protected TextField apellidosTF;
	protected TextField dniTF;
	protected HorizontalLayout dateOfBirthWrapper;
	protected DateField fechacontratacionD;
	protected Label estadoL;
	protected Slider estadoB;
	protected Button aceptarB;
	protected Button cancelarB;

	public AltaModificarComercial_ventana() {
		Design.read(this);
	}
}
