package com.randomteam.ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AltaNuevoCliente_ventana extends CssLayout {
	protected TextField nombreTF;
	protected TextField apellidoTF;
	protected TextField documentoTF;
	protected TextField emailTF;
	protected TextField telefonoTF;
	protected Label movilL;
	protected ComboBox<DB.Movil> movilLS;
	protected Label fijoL;
	protected ComboBox<DB.Fijo> fijoLS;
	protected Label fibraL;
	protected ComboBox<DB.Fibra> fibraLS;
	protected Label televisionL;
	protected ComboBox<DB.Television> televisionLS;
	protected Button terminalesB;
	protected Button darDeAltaB;

	public AltaNuevoCliente_ventana() {
		Design.read(this);
	}
}
