package com.randomteam.ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.Slider;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EditarPaquete_ventana extends CssLayout {
	protected Label nombreL;
	protected TextField nombreTF;
	protected Label estadoL;
	protected Slider estadoSlider;
	protected Grid<DB.Canal> canalesLS;
	protected Button addCanalB;
	protected Button rmCanalB;
	protected Button aceptarB;

	public EditarPaquete_ventana() {
		Design.read(this);
	}
}
