package com.randomteam.ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ListadoIncidencias_ventana extends CssLayout {
	protected TextField buscarTF;
	protected Grid<java.lang.String> cibernautaLS;
	protected Grid<java.lang.String> clienteLS;
	protected Grid<java.lang.String> asignadasLS;
	protected Grid<java.lang.String> completadasLS;
	protected Button asignarB;
	protected Button eliminarB;

	public ListadoIncidencias_ventana() {
		Design.read(this);
	}
}
