package com.randomteam.ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.ProgressBar;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MiCuenta_ventana extends CssLayout {
	protected Label nombreL;
	protected Button mDatosPersonales;
	protected Button mServicios;
	protected Button misFacturas;
	protected Button misIncidencias;
	protected CssLayout consumocss;
	protected ProgressBar consumoBar;
	protected Grid<DB.Servicio> serviciosLS;

	public MiCuenta_ventana() {
		Design.read(this);
	}
}
