package com.randomteam.ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ModificarDatosPersonales_ventana extends CssLayout {
	protected TextField nombreTF;
	protected TextField apellidoTF;
	protected TextField correoTF;
	protected TextField telefonoTF;
	protected Button cancelarB;
	protected Button aceptarB;

	public ModificarDatosPersonales_ventana() {
		Design.read(this);
	}
}
