package com.randomteam.ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NuevaReclamacionComercial_ventana extends VerticalLayout {
	protected Label asuntoL;
	protected Label documentoL;
	protected TextField documentoTF;
	protected TextField asuntoTF;
	protected Label tipoL;
	protected NativeSelect tipoLS;
	protected Label mensajeL;
	protected Button enviarB;
	protected TextArea mensajeTA;

	public NuevaReclamacionComercial_ventana() {
		Design.read(this);
	}
}
