package com.randomteam.ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.v7.ui.NativeSelect;
import com.vaadin.v7.ui.TextField;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NuevaReclamacion_ventana extends VerticalLayout {
	protected Label asuntoL;
	protected TextField asuntoTF;
	protected Label tipoL;
	protected NativeSelect tipoLS;

	public NuevaReclamacion_ventana() {
		Design.read(this);
	}
}
