package com.randomteam.ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TarifasTelevision_ventana extends CssLayout {
	protected Label paquetesTVL;
	protected TextField buscarPaquetesTF;
	protected Grid<DB.Paquete> paquetesLS;
	protected Button crearPaqueteB;
	protected Button eliminarPaqueteB;
	protected Label canalesTVL;
	protected TextField buscarCanalesTF;
	protected Grid<DB.Canal> canalesLS;
	protected Button crearCanalB;
	protected Button eliminarCanalB;

	public TarifasTelevision_ventana() {
		Design.read(this);
	}
}
